modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="miltenmagic" #mandatory

version="1.18.2-0.1.0" #mandatory
# A display name for the mod
displayName="Milten Magic" #mandatory

#logoFile="logo.png" #optional

#credits="Thanks to Wolfgang Hochleitner and Michael Lankes"
authors="Tobias Filler"
description='''
Milten Magic adds a Gothic inspired magic system to Minecraft '''

[[dependencies.miltenmagic]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.miltenmagic]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
